import { Book } from './types';

export const books: Book[] = [
  {
    id: '1',
    name: "Gardner's Art Through the Ages: A Global History",
    shortDescription:
      "The 14TH EDITION of GARDNER'S ART THROUGH THE AGES provides you with a comprehensive, beautifully-illustrated tour of the world's great artistic traditions! ",
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: 'Kleiner, Fred S.',
    ISBN: '9780495915423',
    Edition: '14',
    price: '18.54',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '2',
    name: 'Pocket Medicine: The Massachusetts General Hospital Handbook of Internal Medicine (Pocket Notebook) Fifth Edition',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '3',
    name: 'Study Manual for the Test of Essential Academic Skills, Version 5: Reading, Mathematics, Science, English and Language Usage',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '4',
    name: "PMP Exam Prep, Eighth Edition - Updated: Rita's Course in a Book for Passing the PMP Exam",
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '5',
    name: 'Publication Manual of the American Psychological Association',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '6',
    name: 'The New Art and Science of Teaching Mathematics (Establish Effective Teaching Strategies in Mathematics Instruction)',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '7',
    name: 'A Mind For Numbers: How to Excel at Math and Science (Even If You Flunked Algebra) ',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '8',
    name: 'Math Art: Truth, Beauty, and Equations',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '9',
    name: 'The Science Notebook: Blank and Lined pages',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '10',
    name: 'Science Notebook: Blank and Lined pages (DNA)',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '11',
    name: 'Essential Math for Data Science: Take Control of Your Data with Fundamental Linear Algebra, Probability, and Statistics',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
];

export const myBooks: Book[] = [
  {
    id: '1',
    name: "Gardner's Art Through the Ages: A Global History",
    shortDescription:
      "The 14TH EDITION of GARDNER'S ART THROUGH THE AGES provides you with a comprehensive, beautifully-illustrated tour of the world's great artistic traditions! ",
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: 'Kleiner, Fred S.',
    ISBN: '9780495915423',
    Edition: '14',
    price: '18.54',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '2',
    name: 'Pocket Medicine: The Massachusetts General Hospital Handbook of Internal Medicine (Pocket Notebook) Fifth Edition',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
  {
    id: '3',
    name: 'Study Manual for the Test of Essential Academic Skills, Version 5: Reading, Mathematics, Science, English and Language Usage',
    shortDescription: '',
    coverImage: 'https://images.isbndb.com/covers/54/23/9780495915423.jpg',
    authors: '',
    ISBN: '',
    Edition: '',
    price: '',
    contactEmail: 'hello@noreply.com',
  },
];
